### PR TITLE
🙈 Notebook Cell Tags Documentation

### LINKED ISSUE #1108: Control code cell visibility and behavior with tags and metadata
Currently, all code cells that are parsed by MyST will include their input and outputs together.

Outputs can be inserted into the page via the `{embed}` directive, which allows you to remove the input, output, or include both.

However it's not possible to modify the behavior of the code cell itself, which makes it clunky if you want the code cell to exist on the same page where you want to embed its output.

It would be helpful if there were a way to control the visibility of the cell input and cell output from within a code cell.

### How MyST-NB handles this

MyST NB accomplishes this by [using Cell Metadata tags](https://myst-nb.readthedocs.io/en/latest/configuration.html#cell-tags), with tags like the following:

- `remove-cell`
- `remove-input`
- `remove-output`
- `hide-input` (hides behind a toggle)
- `hide-output`
- `skip-execution`
- `raises-exception` (to prevent errors from stopping the build process)

### PR DESCRIPTION
**Pull request by rowanc1**
See also:

- jupyter-book/myst-theme#517
- Fixes #1108

### CODE REVIEW

File: packages/myst-execute/src/execute.ts [hunk 1]
```diff
@@ -175,15 +175,15 @@ function isCellBlock(node: GenericNode): node is CodeBlock {
...
+  return !!node.data?.tags?.includes?.(NotebookCellTags.raisesException);
 }
 /**
  * Return true if the given code block should not be executed
  *
  * @param node block to test
  */
 function codeBlockSkipsExecution(node: CodeBlock) {
-  return !!node.data?.tags?.includes?.('skip-execution');
+  return !!node.data?.tags?.includes?.(NotebookCellTags.skipExecution);
```
Comment (agoose77) [inline packages/myst-execute/src/execute.ts:186]: Much better!

Comment (rowanc1) [reply packages/myst-execute/src/execute.ts:186]: Small little improvements. I was in there looking to implement this and was surprised it was already done!
