### PR TITLE
⚠️ Improve error messages for `myst templates download` command

### LINKED ISSUE #2033: `myst templates download` does not provide helpful error messages
## Description
When running `myst templates download`, it did not seem possible to escape the error:
> `Cannot lookup a template with more than one kind`. 

Upon further inspection, I realised that this was a [PEBKAC](https://en.wikipedia.org/wiki/User_error), and one is supposed to pass the template type as a CLI flag. However, I _did_ take a closer look at the source code in the process.

I'll work up a small PR to improve the error messages here.

### PR DESCRIPTION
**Pull request by agoose77**
In pursuing #2033, I discovered that the error messages for `myst templates download` were not intuitive.

This PR closes #2033 by rewording the errors to make recovery steps clearer.

### CODE REVIEW

File: packages/mystmd/src/templates.ts [hunk 1]
```diff
@@ -63,8 +63,12 @@ export async function downloadTemplateCLI(
 ) {
   const templateKind = getKindFromName(template);
   const kinds = templateKind ? [templateKind] : getKind(session, opts);
-  if (!kinds || kinds.length > 1) {
-    throw new Error('Cannot lookup a template with more than one kind.');
+  if (!kinds || !kinds.length) {
```
Comment (agoose77) [inline packages/mystmd/src/templates.ts:66]:
```suggestion
  if (!kinds?.length) {
```

**Comment by agoose77** [comment]
@roaldarbol would you mind reading over this PR change and see whether these error message changes would have been helpful for you in your recent usage of the `myst templates download` command?

If you don't have time to do this, let me know. If I don't hear from you by Thur 22nd, I'll merge it in my morning (BST) -- so no pressure.

**Comment by roaldarbol** [comment]
Just a quick comment, is there a reason why it's `kind` in the CLI, but `format` in `myst.yml`? I find that a bit confusing. Also, what inputs does it take? A full URL? ghorg/ghrepo? Maybe add a bit of extra info to `myst templates --help`. 
Quarto has the following for `quarto add --help`, notice especially the last three lines with examples, I find them very helpful:
```sh
❯ quarto add --help

Usage:   quarto add <extension>
Version: 1.7.24

Description:

  Add an extension to this folder or project

Options:

  -h, --help                   - Show this help.
  --no-prompt                  - Do not prompt to confirm actions
  --embed       <extensionId>  - Embed this extension within another extension (used when authoring extensions).
  --log         <file>         - Path to log file
  --log-level   <level>        - Log level (info, warning, error, critical)
  --log-format  <format>       - Log format (plain, json-stream)
  --quiet                      - Suppress console output.
  --profile                    - Active project profile(s)

Commands:

  help  [command]  - Show this help or the help of a sub-command.

Examples:

  Install extension (Github): quarto add <gh-org>/<gh-repo>
  Install extension (file):   quarto add <path-to-zip>
  Install extension (url):    quarto add <url>
  ```

**Comment by roaldarbol** [comment]
Just tried with a template that's actually listed on `myst templates list`, which also doesn't work, so I definitely think it needs to be much clearer what is expected:
```
❯ myst templates download lapreprint-typst
Cannot lookup a template with more than one kind.
```

Prefixing with `typst/` gets me closer, but then it's duplicated in the URL:
```
❯ myst templates download typst/lapreprint-typst
🔍 Querying template metadata from https://api.mystmd.org/templates/typst/typst/lapreprint-typst
Problem with template link "https://api.mystmd.org/templates/typst/typst/lapreprint-typst": 404 Not Found
```

**Comment by agoose77** [comment]
@roaldarbol running this PR, I see:
```
❯ myst templates download lapreprint-typst
Cannot lookup a template without specifying a kind (e.g. typst).
```

Passing `--typst` works:

```
❯ myst templates download lapreprint-typst  --typst
🔍 Querying template metadata from https://api.mystmd.org/templates/typst/myst/lapreprint-typst
🐕 Fetching template from https://github.com/myst-templates/lapreprint-typst/archive/refs/heads/main.zip
💾 Saved template to path _build/templates/typst/myst/lapreprint-typst

Then, the full canonical ID works
```
❯ myst templates download typst/myst/lapreprint-typst
🔍 Querying template metadata from https://api.mystmd.org/templates/typst/myst/lapreprint-typst
🐕 Fetching template from https://github.com/myst-templates/lapreprint-typst/archive/refs/heads/main.zip
💾 Saved template to path _build/templates/typst/myst/lapreprint-typst
```

Regarding `kind` vs `format` — yes, that seems confusing. I wonder if we can standardise that at the CLI level for now. We could also add a custom help message with examples, if the new help info isn't useful enough!

**Comment by roaldarbol** [comment]
> Passing `--typst` works:

This is what needs to be said! 😃 Where would a user know that from? That would be great info to place somewhere in the messages. 😊

> Then, the full canonical ID works

And this of course too. It's exactly the kind of info that's useful - what does a user need to do to *not* get an error.

**Comment by agoose77** [comment]
> > Passing `--typst` works:
> 
> This is what needs to be said! 😃 Where would a user know that from? That would be great info to place somewhere in the messages. 😊

In theory, a user would inspect the CLI help and see the various flags. I think the help for these flags is not as good as it could be - it should be more clear that these are used to help myst figure out the template ID. I also wonder whether we can fall back on _not_ needing these for templates with only one kind. I know that the use of the MyST API server is being discussed, so we can probably handle that then. 

> > Then, the full canonical ID works

> And this of course too. It's exactly the kind of info that's useful - what does a user need to do to *not* get an error.

Yes, the canonical ID is not obvious, and I had to remind myself of its format.

**Comment by roaldarbol** [comment]
I think you could likely add some changes for the `--help` into this PR (though of course you may wish to do it elsewhere). The current `--help` doesn't mention `kind` at all.
```sh
❯ myst templates --help
Usage: myst templates [options] [command]

List and download templates

Options:
  -h, --help                            display help for command

Commands:
  list [options] [name]                 List, filter or lookup details on
                                        public templates
  download [options] <template> [path]  Download a public template to a path
  help [command]                        display help for command
  ```

**Comment by roaldarbol** [comment]
Ah, there's *another* nested `--help` for `download`! It's *not* clear at all that one oculd get help so far down 😃 This one is better, though maybe I'd still like to know that one has to *either* provide a `kind` flag (`such as --typst or --docx`) or a canonical URL. Or let the user know that they can see options with `myst templates download --help`.
Just adding the output for reference:
```sh
❯ myst templates download --help
Usage: myst templates download [options] <template> [path]

Download a public template to a path

Arguments:
  template        The template URL or name
  path            A folder to download and unzip the template to

Options:
  --pdf           Download PDF template (default: false)
  --tex           Download LaTeX template (default: false)
  --typst         Download Typst template (default: false)
  --word, --docx  Download Docx template (default: false)
  --site          Download Site template (default: false)
  --force         Build outputs for the given format, even if corresponding
                  exports are not defined in file frontmatter (default: false)
  -h, --help      display help for command
  ```

**Comment by agoose77** [comment]
There's definitely more to do here, but I am also aware that we really want to make wider changes in the near future (see #2041). So, I'm going to merge this PR as-is as an incremental improvement, to try and get some of the in-flight work merged.

**Comment by roaldarbol** [comment]
Makes complete sense. #2041 looks great btw!
