### PR TITLE
✍️ Report tracebacks during kernel execution

### LINKED ISSUE #1117: Document `stderr` and `stdout` for cell and eval execution
Currently if you execute a notebook and it returns errors, you get a MyST log message like:

```
⚠️  notebooks-with-markdown.md An exception occurred during expression evaluation, halting further execution
⛔️ notebooks-with-markdown.md An error occurred during kernel execution
📖 Built notebooks-with-markdown.md in 1.39 s.
⚠️  interactive-notebooks.ipynb An exception occurred during code execution, halting further execution
⛔️ interactive-notebooks.ipynb An error occurred during kernel execution
📖 Built interactive-notebooks.ipynb in 2.2 s.
```

This doesn't give you much information to understand what happened. It would be useful to surface the execution logs so that you can see what's going on.

Two ways you could do this:

1. In the MyST build logs (e.g. show the execution errors with `myst build --execute -d`.
2. In the build outputs (e.g. have a `_build/execute/page1_logs.txt` file)

Of the two I think the second would be more user friendly, so that you could surface a link to the logs in the MyST build log, and then the more verbose execution logs could be browsed via a file browser.

### PR DESCRIPTION
**Pull request by agoose77**
Fixes #1117 

Later on we probably want to move this out of the logs into a dedicated file. However, this is an incremental improvement.

### CODE REVIEW

File: packages/myst-execute/src/execute.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ import type { PageFrontmatter } from 'myst-frontmatter';
 import type { Kernel, KernelMessage, Session, SessionManager } from '@jupyterlab/services';
 import type { Code, InlineExpression } from 'myst-spec-ext';
 import type { IOutput } from '@jupyterlab/nbformat';
-import type { GenericNode, GenericParent, IExpressionResult } from 'myst-common';
+import type { GenericNode, GenericParent, IExpressionResult, IExpressionError } from 'myst-common';
 import { NotebookCell, fileError, fileWarn } from 'myst-common';
```
Comment (rowanc1) [inline packages/myst-execute/src/execute.ts:8]:
```suggestion
import { NotebookCell, fileError } from 'myst-common';
```
