### PR TITLE
🔄 Fetch with Retry for HTML build

### LINKED ISSUE #1775: Export to html often fails when trying to serve many pages
I can build the site, but export to html often fails and in a stochastic way.

v1.3.20

See attachments for log files.

[log5.log](https://github.com/user-attachments/files/18398049/log5.log)
[log6.log](https://github.com/user-attachments/files/18398047/log6.log)
[log7.log](https://github.com/user-attachments/files/18398048/log7.log)

## Description

As my site has grown, the conversion to html has started to fail often. I get ECONNRESET or EPIPE errors after the app begins making requests to the web server to pull html pages. If I run `myst build --execute --html` 20 times, it might succeed once or twice.

## Proposed solution

My best guess is that the server is becoming overwhelmed with what amounts to a DOS attack. I tried setting `NODE_OPTIONS="--max-old-space-size=4096"`, but it did not seem to help.

Maybe the exporter can slow down page requests a little, or buffer them?

### PR DESCRIPTION
**Pull request by rowanc1**
Limits outgoing connections to five.

Fixes #1775
See also #1336

### CODE REVIEW

File: packages/myst-cli/src/build/html/index.ts [hunk 1]
```diff
@@ -141,25 +145,27 @@ export async function buildHtml(session: ISession, opts: StartOptions) {
...
-          fileWriteStream.on('finish', resolve);
-        });
-      } else {
-        const content = await resp.text();
-        writeFileToFolder(path.join(htmlDir, route.path), content);
-      }
-    }),
+    routes.map(async (route) =>
+      limitConnections(async () => {
+        const resp = await fetchWithRetry(session, route.url);
```
Comment (rowanc1) [inline packages/myst-cli/src/build/html/index.ts:150]: Main changes here, limiting connections to 5 and having a retry with exponential backoff.
